export const siteConfig = {
  name: '渐近自由',
  title: '渐近自由｜物理笔记与长文',
  description: '从模型出发，向结构深入。读书时记下的推导、问题和偶尔想明白的事情。',
  author: 'AsyaInTheCosmicStatic',
  language: 'zh-CN',
  nav: [
    { label: '文章', href: '/articles/' },
    { label: '笔记', href: '/notes/' },
    { label: '归档', href: '/archive/' },
    { label: '关于', href: '/about/' },
    { label: '搜索', href: '/search/' },
  ],
  features: {
    search: true,
    comments: false,
    studyRoom: true,
    music: true,
    wallpaper: true,
    stats: true,
    mermaid: true,
    lightbox: true,
    readingProgress: true,
  },
  repositoryUrl: 'https://github.com/hhhssccc/phase-space-notes',
  mascot: {
    idle: '/assets/mascot-idle.webp',
    reading: '/assets/mascot-reading.webp',
    studyAvatar: '/assets/mascot-study-avatar.webp',
    name: '宇佐见莲子',
  },
  giscus: {
    repo: import.meta.env.PUBLIC_GISCUS_REPO || '',
    repoId: import.meta.env.PUBLIC_GISCUS_REPO_ID || '',
    categoryId: import.meta.env.PUBLIC_GISCUS_CATEGORY_ID || '',
  },
} as const;
